config/routes.rb
Spree::Core::Engine.routes.prepend do
  namespace :admin do
    resource :fetch_app_settings

    resources :orders do
      member do 
        get :fetch_app_synch
      end
      collection do 
        get :fetch_app_synch_all
      end
    end

    resources :products do
      member do 
        get :fetch_app_synch
      end
      collection do 
        get :fetch_app_synch_all
      end
    end
  end
end

app/controllers/spree/admin/fetch_app_settings_controller.rb
module Spree
  module Admin
    class FetchAppSettingsController < BaseController

      def update
        SpreeFetchApp::Config.set(params[:preferences])

        respond_to do |format|
          format.html {
            redirect_to admin_fetch_app_settings_path
          }
        end
      end

    end
  end
end

app/views/spree/admin/fetch_app_settings/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1><%= t(:fetch_app_settings) %></h1>

  <%= link_to t(:fetch_app_signup), 'http://www.fetchapp.com/' %>

<%= form_tag admin_fetch_app_settings_path, :method => :put do %>

    <%= label_tag('app_name', t(:fetch_app_app_name) + ': ') + tag(:br) %>
    <%# I wanted to use preference_field_tag, but the text field size is locked in at 10! %>
    <%= text_field_tag 'preferences[app_name]', SpreeFetchApp::Config[:app_name], :size => "30", :class => "input_string" %>
    <br/>

    <%= label_tag('api_key', t(:fetch_app_api_key) + ': ') + tag(:br) %>
    <%= text_field_tag 'preferences[api_key]', SpreeFetchApp::Config[:api_key], :size => "20", :class => "input_string" %>
    <br/>

    <%= label_tag('api_token', t(:fetch_app_api_token) + ': ') + tag(:br) %>
    <%= text_field_tag 'preferences[api_token]', SpreeFetchApp::Config[:api_token], :size => "20", :class => "input_string" %>
    <br/>

    <%= label_tag('push_on_order_complete', t(:fetch_app_push_on_order_complete) + ': ') + tag(:br) %>
    <%= hidden_field_tag('preferences[push_on_order_complete]', 0) %>
    <%= check_box_tag 'preferences[push_on_order_complete]', 1, SpreeFetchApp::Config[:push_on_order_complete], :size => "20", :class => "input_string" %>
    <br/>

  <p class="form-buttons">
    <%= button t(:update) %>
    <%= t(:or) %> <%= link_to t(:cancel), admin_fetch_app_settings_url %>
  </p>

<% end %>

app/views/spree/admin/fetch_app_settings/show.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1><%= t(:fetch_app_settings) %></h1>

<table id='listing_fetch_app_settings'>
  <tr>
    <th scope="row"><%= t(:fetch_app_app_name) %>:</th>
    <td><%= SpreeFetchApp::Config[:app_name] %></td>
  </tr>
  <tr>
    <th scope="row"><%= t(:fetch_app_api_key) %>:</th>
    <td><%= SpreeFetchApp::Config[:api_key] %></td>
  </tr>
  <tr>
    <th scope="row"><%= t(:fetch_app_api_token) %>:</th>
    <td><%= SpreeFetchApp::Config[:api_token] %></td>
  </tr>
  <tr>
    <th scope="row"><%= t(:fetch_app_push_on_order_complete) %>:</th>
    <td><%= SpreeFetchApp::Config[:push_on_order_complete] %></td>
  </tr>
</table>

<p data-hook="buttons">
  <%= link_to_with_icon 'edit', t(:edit), edit_admin_fetch_app_settings_path %>
</p>